-- MySQL Script generated by MySQL Workbench
-- Sat May 15 15:22:40 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users`
(
    `id`         INT          NOT NULL AUTO_INCREMENT,
    `username`   VARCHAR(31)  NOT NULL,
    `email`      VARCHAR(127) NOT NULL,
    `password`   VARCHAR(255) NOT NULL,
    `phone`      VARCHAR(31)  NULL,
    `first_name` VARCHAR(63)  NOT NULL,
    `last_name`  VARCHAR(63)  NOT NULL,
    `is_active`  BOOLEAN      NOT NULL,
    `role`       INT          NOT NULL,
    PRIMARY KEY (`id`)
);

CREATE UNIQUE INDEX `email_UNIQUE` ON `users` (`email` ASC);

CREATE UNIQUE INDEX `username_UNIQUE` ON `users` (`username` ASC);

CREATE TABLE IF NOT EXISTS `role`
(
    `id`         INT          NOT NULL AUTO_INCREMENT,
    `name`       VARCHAR(31)  NOT NULL,
    PRIMARY KEY (`id`)
);

-- -----------------------------------------------------
-- Table `confirm_token`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `confirm_token`
(
    `token_id`              INT             NOT NULL AUTO_INCREMENT,
    `users_id`              INT             NOT NULL,
    `confirmation_token`    VARCHAR(255)    NOT NULL,
    `created_date`          DATETIME        NOT NULL,
    CONSTRAINT `fk_confirm_token_users1`
        FOREIGN KEY (`users_id`)
            REFERENCES `users` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    PRIMARY KEY (`token_id`)
);

CREATE UNIQUE INDEX `fk_confirm_token_users1_idx` ON `confirm_token` (`users_id` ASC);


-- -----------------------------------------------------
-- Table `account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `account`
(
    `id`           INT                      NOT NULL AUTO_INCREMENT,
    `name`         VARCHAR(45)              NOT NULL,
    `type`         VARCHAR(255)             NOT NULL,
    `allow_credit` BOOLEAN                  NOT NULL DEFAULT 0,
    `credit_limit` DECIMAL(20, 2)           NOT NULL DEFAULT 0,
    `allow_cards`  BOOLEAN                  NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`)
);


-- -----------------------------------------------------
-- Table `user_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_account`
(
    `account_number` VARCHAR(31)    NOT NULL,
    `users_id`       INT            NOT NULL,
    `account_id`     INT            NOT NULL,
    `balance`        DECIMAL(20, 2) NOT NULL,
    `active`         BOOLEAN        NOT NULL,
    PRIMARY KEY (`account_number`),
    CONSTRAINT `fk_users_has_account_users1`
        FOREIGN KEY (`users_id`)
            REFERENCES `users` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_users_has_account_account1`
        FOREIGN KEY (`account_id`)
            REFERENCES `account` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
);

CREATE INDEX `fk_users_has_account_account1_idx` ON `user_account` (`account_id` ASC);

CREATE INDEX `fk_users_has_account_users1_idx` ON `user_account` (`users_id` ASC);

-- -----------------------------------------------------
-- Table `user_account_confirmation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_account_confirmation` (
    `user_account_id`   VARCHAR(31)     NOT NULL,
    `code`              VARCHAR(255)    NOT NULL,
    `expires`           DATETIME        NOT NULL,
    PRIMARY KEY (`user_account_id`),
    CONSTRAINT `fk_user_account_confirmation_has_user_account1`
        FOREIGN KEY (`user_account_id`)
            REFERENCES `user_account` (`account_number`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
);

CREATE INDEX `fk_user_account_confirmation_has_user_account1_idx` ON `user_account_confirmation` (`user_account_id` ASC);
CREATE INDEX `code_UNIQUE` ON `user_account_confirmation` (`code`);


-- -----------------------------------------------------
-- Table `transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transaction`
(
    `id`             INT            NOT NULL AUTO_INCREMENT,
    `account_number` VARCHAR(31)    NOT NULL,
    `amount`         DECIMAL(20, 2) NOT NULL,
    `timestamp`      TIMESTAMP      NOT NULL,
    `message`        VARCHAR(255)   NOT NULL,
    `status`         VARCHAR(31)    NOT NULL,
    `destination`    VARCHAR(255)   NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_transaction_user_account1`
        FOREIGN KEY (`account_number`)
            REFERENCES `user_account` (`account_number`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
);

CREATE INDEX `fk_transaction_user_account1_idx` ON `transaction` (`account_number` ASC);


-- -----------------------------------------------------
-- Table `card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `card`
(
    `id`             INT         NOT NULL AUTO_INCREMENT,
    `account_number` VARCHAR(31) NOT NULL,
    `card_number`    VARCHAR(31) NOT NULL,
    `exp`            DATE        NOT NULL,
    `cvv`            VARCHAR(3)  NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_card_user_account1`
        FOREIGN KEY (`account_number`)
            REFERENCES `user_account` (`account_number`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
);

CREATE INDEX `fk_card_user_account1_idx` ON `card` (`account_number` ASC);
